################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
################################################################################

source-list:
  #semicolon separated uri. For ex- uri1;uri2;uriN;
  # list: file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_1080p_h264.mp4;file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_1080p_h264.mp4;
  list: rtsp://localhost:8554/mystream;rtsp://localhost:8554/mystream;

streammux:
  batch-size: 2
  batched-push-timeout: 40000
  width: 1920
  height: 1080
  live-source: 1
  sync-inputs: 1
  attach-sys-ts: 1

osd:
  process-mode: 1
  display-text: 1

tiler:
  width: 1280
  height: 720

sink:
  qos: 1
  sync: 1
  async: 0

# Inference using nvinfer:
primary-gie:
  plugin-type: 0
  config-file-path: dstest3_pgie_config.yml

## Inference using nvinferserver:
#primary-gie:
#  plugin-type: 1
#  config-file-path: dstest3_pgie_nvinferserver_config.txt
